---
title: "R_Markdown"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Exercise 1

```{r}
creditrisk_data <- read.csv("creditrisk.csv", header = TRUE)
creditrisk_data
```

```{r}
names(creditrisk_data)
head(creditrisk_data)
tail(creditrisk_data)
str(creditrisk_data)
summary(creditrisk_data)
dim(creditrisk_data)
```

```{r}
# Split data into train and test data
set.seed(1234)

pd <- sample(2, nrow(creditrisk_data), replace = TRUE, prob = c(0.60,0.40))
training_data <- creditrisk_data[pd==1,]
test_data <- creditrisk_data[pd==2,]
dim(training_data)
dim(test_data)
```

```{r}
# Install neuralnet for ANN training model
install.packages("neuralnet")
library(neuralnet)
```

```{r}
creditnet <-neuralnet(default10yr ~ LTIR+age, training_data, hidden = 3, lifesign = "minimal", linear.output = FALSE, threshold = 0.1)
plot(creditnet, rep = "best")
```

```{r}
temp_test <- subset(test_data, select = c("LTIR", "age"))
head(temp_test)
```

```{r}
creditnet_results <- compute(creditnet, temp_test)

names(creditnet_results)
str(creditnet_results)
```

```{r}
results <- data.frame(actual = test_data$default10yr, prediction =creditnet_results$net.result)
head(results)
tail(results)

results[90:105,]
```

```{r}
results$prediction <- sapply(creditnet_results$net.result, round, digits = 0)
results[90:105,]
```

```{r}
# Confusion Matrix

confusionmatrix <- table(test_data$default10yr, results$prediction)
print(confusionmatrix)
```

```{r}
# Classificaiton accuracy
sum(diag(confusionmatrix))/sum(confusionmatrix)

# Or classification error
1 - sum(diag(confusionmatrix))/sum(confusionmatrix)
```

# Exercise 2

```{r}
creditnet2 <- neuralnet(default10yr ~ income+age+loan+LTIR, training_data, hidden = 3, lifesign = "minimal", linear.output = FALSE, threshold = 0.1)
plot(creditnet2, rep = "best")
```

```{r}
temp_test2 <- subset(test_data, select = c("income", "age", "loan", "LTIR"))
head(temp_test2)
```

```{r}
creditnet2_results <- compute(creditnet2, temp_test2)

names(creditnet2_results)
str(creditnet2_results)
```

```{r}
results2 <- data.frame(actual = test_data$default10yr, prediction = creditnet2_results$net.result)
results2[90:105,]
```

```{r}
results2$prediction <- sapply(creditnet2_results$net.result, round, digits = 0)
results2[90:105,]
```

```{r}
# Confusion Matrix
confusionmatrix2 <- table(test_data$default10yr, results2$prediction)
print(confusionmatrix2)
```

```{r}
# Classification accuracy
sum(diag(confusionmatrix2))/sum(confusionmatrix2)
```

# Part 2 : Exercise

```{r}
cardio_data <- read.csv("Cardiotocographic.csv", header = TRUE)
cardio_data
```

```{r}
names(cardio_data)
head(cardio_data)
tail(cardio_data)
str(cardio_data)
summary(cardio_data)
```

```{r}
# Convert NSP value into categorical values
cardio_data$NSP <- as.factor(cardio_data$NSP)
```

```{r}
set.seed(1234)
pd <- sample(2, nrow(cardio_data), replace = TRUE, prob = c(0.70, 0.30))
pd
```

```{r}
# Split data into test and train data
train_data <- cardio_data[pd==1,]
test_data <- cardio_data[pd==2,]
```

```{r}
library(party)
```

```{r}
cardio_tree <- ctree(NSP ~ BPM+APC+FMPS+UCPS, data = train_data)
cardio_tree
```

```{r} 
plot(cardio_tree, type = "simple")
```

```{r}
predict(cardio_tree)
```

```{r}
tab <- table(predict(cardio_tree), train_data$NSP)
tab
```

```{r}
# Classification accuracy
sum(diag(tab))/sum(tab)
```

```{r}
test_predict <- table(predict(cardio_tree, newdata = test_data), test_data$NSP)
test_predict
```

```{r}
# Classification accuracy
sum(diag(test_predict))/sum(test_predict)
```

```{r}
cardio_data$NSP <- as.integer(cardio_data$NSP)
str(cardio_data)
```

```{r}
cardionet <- neuralnet(NSP ~ BPM+APC+FMPS+UCPS, train_data, hidden = c(3,2), lifesign = "minimal", linear.output = FALSE, threshold = 0.1)
plot(cardionet, rep = "best")
```

```{r}
temp_test <- subset(test_data, select = c("BPM", "APC", "FMPS", "UCPS"))
head(temp_test)
```

```{r}
cardionet_results <- compute(cardionet, temp_test)
names(cardionet_results)
str(cardionet_results)
```

```{r}
results <- data.frame(actual = test_data$NSP, prediction = cardionet_results$net.result)
head(results)
```

```{r}
results$prediction <- sapply(cardionet_results$net.result, round, digits = 0)
```

```{r}
confusionmatrix <- table(test_data$NSP, results$prediction)
confusionmatrix
```

```{r}
# Classification accuracy
sum(diag(confusionmatrix))/sum(confusionmatrix)
```

