---
title: "R_Markdown"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Exercise

```{r}
# Import dataset

cardio_data <- read.csv("Cardiotocographic.csv", header = TRUE)
cardio_data
```

```{r}
# Statistic Summary
names(cardio_data)
head(cardio_data)
tail(cardio_data)
str(cardio_data)
summary(cardio_data)
```

```{r}
# Convert NSP value into factor for categorical variables
cardio_data$NSP <- as.factor(cardio_data$NSP)
str(cardio_data)
```

```{r}
# Divide dataset into two data category : train set and test set
set.seed(1234)
pd <- sample(2, nrow(cardio_data), replace = TRUE, prob = c(0.8,0.2))
pd
```

```{r}
# Assign train set and test set to repective variable
train <- cardio_data[pd==1,]
test <- cardio_data[pd==2,]
dim(train)
dim(test)
```

```{r}
# Install party package for decision tree 
library(party)
```

```{r}
cardio_tree <- ctree(NSP ~ BPM+APC+FMPS+UCPS, data = train)
cardio_tree
```

```{r}
plot(cardio_tree, type = "simple")
```

```{r}
# Data prediction
predict(cardio_tree)
```

```{r}
# Accuracy table between predicted tree and train dataset
tab <- table(predict(cardio_tree), train$NSP)
tab
```

```{r}
# Classification accuracy
sum(diag(tab))/sum(tab)

# Or classification error
1 - sum(diag(tab))/sum(tab)
```

```{r}
# Prediction on test dataset
test_predict <- table(predict(cardio_tree, newdata = test), test$NSP)
test_predict
```

```{r}
# Classification accuracy on test dataset
sum(diag(test_predict))/sum(test_predict)

# Classification error
1 - sum(diag(test_predict))/sum(test_predict)
```

