---
title: "R_Markdown"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Exercise

```{r}
library(tm)
library(wordcloud)
```

```{r}
reviews <- read.csv("reviews_of_Amazon_Products.csv", header = TRUE)
reviews
```

```{r}
names(reviews)
head(reviews)
tail(reviews)
str(reviews)
summary(reviews)
dim(reviews)
```

```{r}
R_16GB_Blue<-subset(reviews,name=="Fire HD 8 Tablet, Wi-Fi, 16 GB-Blue")
R_16GB_Magenta<-subset(reviews,name=="Fire HD 8 Tablet,  Wi-Fi, 16 GB-Magenta")
R_32GB_Blue<-subset(reviews,name=="Fire HD 8 Tablet, Wi-Fi, 32 GB-Blue")
R_32GB_Magenta<-subset(reviews,name=="Fire HD 8 Tablet,  Wi-Fi, 32 GB-Magenta")
R_32GB_Black<-subset(reviews,name=="Fire HD 8 Tablet,  Wi-Fi, 32 GB-Black")
```

```{r}
head(R_16GB_Blue$reviews.text)
head(R_16GB_Magenta$reviews.text)
head(R_32GB_Blue$reviews.text)
head(R_32GB_Magenta$reviews.text)
head(R_32GB_Black$reviews.text)
```

```{r}
review_16GB_Blue<-R_16GB_Blue$reviews.text
review_16GB_Magenta<-R_16GB_Magenta$reviews.text
review_32GB_Blue<-R_32GB_Blue$reviews.text
review_32GB_Magenta<-R_32GB_Magenta$reviews.text
review_32GB_Black<-R_32GB_Black$reviews.text
```

```{r}
review_16GB_Blue<-tolower(review_16GB_Blue)
review_32GB_Blue<-tolower(review_32GB_Blue)
review_32GB_Magenta<-tolower(review_32GB_Magenta)
review_32GB_Black<-tolower(review_32GB_Black)
```

```{r}
#Remove links from review
review_16GB_Blue <- gsub("http\\S+\\s*", "", review_16GB_Blue)
review_32GB_Blue <- gsub("http\\S+\\s*", "", review_32GB_Blue)
review_32GB_Magenta <- gsub("http\\S+\\s*", "", review_32GB_Magenta)
review_32GB_Black <- gsub("http\\S+\\s*", "", review_32GB_Black)

# Remove punctuation from review
review_16GB_Blue <- gsub("[[:punct:]]", "", review_16GB_Blue)
review_32GB_Blue <- gsub("[[:punct:]]", "", review_32GB_Blue)
review_32GB_Magenta <- gsub("[[:punct:]]", "", review_32GB_Magenta)
review_32GB_Black <- gsub("[[:punct:]]", "", review_32GB_Black)

# Remove digits from review
review_16GB_Blue <- gsub("[[:digit:]]", "", review_16GB_Blue)
review_32GB_Blue <- gsub("[[:digit:]]", "", review_32GB_Blue)
review_32GB_Magenta <- gsub("[[:digit:]]", "", review_32GB_Magenta)
review_32GB_Black <- gsub("[[:digit:]]", "", review_32GB_Black)

# Remove blank space at the beginning of the reviews
review_16GB_Blue <- gsub("^ ", "", review_16GB_Blue)
review_32GB_Blue <- gsub("^ ", "", review_32GB_Blue)
review_32GB_Magenta <- gsub("^ ", "", review_32GB_Magenta)
review_32GB_Black <- gsub("^ ", "", review_32GB_Black)

# Remove blank space at the end of the reviews
review_16GB_Blue <- gsub(" $", "", review_16GB_Blue)
review_32GB_Blue <- gsub(" $", "", review_32GB_Blue)
review_32GB_Magenta <- gsub(" $", "", review_32GB_Magenta)
review_32GB_Black <- gsub(" $", "", review_32GB_Black)

# Remove tablet word from reviews
review_16GB_Blue <- gsub("tablet", "", review_16GB_Blue)
review_32GB_Blue <- gsub("tablet", "", review_32GB_Blue)
review_32GB_Magenta <- gsub("tablet", "", review_32GB_Magenta)
review_32GB_Black <- gsub("tablet", "", review_32GB_Black)
```

```{r}
head(review_16GB_Blue)
head(review_32GB_Blue)
head(review_32GB_Magenta)
head(review_32GB_Black)
```

```{r}
# Transform text file into corpus documents
corpus_16GB_Blue <- Corpus(VectorSource(review_16GB_Blue))
corpus_32GB_Blue <- Corpus(VectorSource(review_32GB_Blue))
corpus_32GB_Magenta <- Corpus(VectorSource(review_32GB_Magenta))
corpus_32GB_Black <- Corpus(VectorSource(review_32GB_Black))
```

```{r}
# Clean up the corpus by removing stopwords and whitespace
corpus_16GB_Blue <- tm_map(corpus_16GB_Blue, removeWords,stopwords("english"))
corpus_16GB_Blue <- tm_map(corpus_16GB_Blue, stripWhitespace)
inspect(corpus_16GB_Blue)

corpus_32GB_Blue <- tm_map(corpus_32GB_Blue, removeWords,stopwords("english"))
corpus_32GB_Blue <- tm_map(corpus_32GB_Blue, stripWhitespace)
inspect(corpus_32GB_Blue)

corpus_32GB_Magenta<-tm_map(corpus_32GB_Magenta, removeWords,stopwords("english"))
corpus_32GB_Magenta <- tm_map(corpus_32GB_Magenta, stripWhitespace)
inspect(corpus_32GB_Magenta)

corpus_32GB_Black <- tm_map(corpus_32GB_Black, removeWords,stopwords("english"))
corpus_32GB_Black <- tm_map(corpus_32GB_Black, stripWhitespace)
inspect(corpus_32GB_Black)
```

```{r}
stem_corpus_16GB_Blue <- tm_map(corpus_16GB_Blue, stemDocument)
stem_corpus_32GB_Blue <- tm_map(corpus_32GB_Blue, stemDocument)
stem_corpus_32GB_Magenta <- tm_map(corpus_32GB_Magenta, stemDocument)
stem_corpus_32GB_Black <- tm_map(corpus_32GB_Black, stemDocument)
```

```{r}
positive_lexicon <- read.csv("positive-lexicon.txt")
negative_lexicon <- read.csv("negative-lexicon.txt")
```

```{r}
sentiment <- function(stem_corpus)
{
  #generate wordclouds
  wordcloud(stem_corpus,
  min.freq = 3,
  colors=brewer.pal(8, "Dark2"),
  random.color = TRUE,
  max.words = 100)
  
  #Calculating the count of total positive and negative words in each review
  
  #Create variables and vectors
  total_pos_count <- 0
  total_neg_count <- 0
  pos_count_vector <- c()
  neg_count_vector <- c()
  
  #Calculate the size of the corpus
  size <- length(stem_corpus)
  
  for(i in 1:size)
  {
    #All the words in current review
    corpus_words<- list(strsplit(stem_corpus[[i]]$content, split = " "))
    #positive words in current review
    
    pos_count <-length(intersect(unlist(corpus_words), unlist(positive_lexicon)))
    
    #negative words in current review
    neg_count <- length(intersect(unlist(corpus_words), unlist(negative_lexicon)))
    total_pos_count <- total_pos_count + pos_count ## overall positive count
    total_neg_count <- total_neg_count + neg_count ## overall negative count
  }
  #Calculating overall percentage of positive and negative words of all the reviews
  total_pos_count ## overall positive count
  total_neg_count ## overall negative count
  total_count <- total_pos_count + total_neg_count
  
  overall_positive_percentage <- (total_pos_count*100)/total_count
  overall_negative_percentage <- (total_neg_count*100)/total_count
  overall_positive_percentage ## overall positive percentage
  #Create a dataframe with all the positive and negative reviews
  df<-data.frame(Review_Type=c("Postive","Negative"),
  Count=c(total_pos_count ,total_neg_count ))
  print(df) #Print
  overall_positive_percentage<-paste("Percentage of Positive Reviews:",
  round(overall_positive_percentage,2),"%")
  return(overall_positive_percentage)
}
```

```{r}
sentiment(stem_corpus_16GB_Blue)
```

```{r}
sentiment(stem_corpus_32GB_Blue)
```

```{r}
sentiment(stem_corpus_32GB_Magenta)
```

```{r}
sentiment(stem_corpus_32GB_Black)
```

